model:
  n_embed: 512     #Hidden size
  block_size: 1024 #
  num_layers: 4
  num_head: 8
  dropout_prob: 0.1

attention:
  # options: 'mha', 'mqa', 'gqa'
  type: mqa
  # if true, use a sliding-window attention mask for masked attention blocks else Causal attention mask
  sliding_window_mask: false
  window_size: 512
  # positional encoding type: 'none', 'learnable', 'alibi', 'rope'
  positional_encoding: learnable
  # group size for Grouped Query Attention (GQA)
  group_size: 2
  # if true, use depthwise Conv1D inside attention blocks
  use_local_conv: false
  # kernel size for local Conv1D inside attention
  ngram_size: 3
  # base for Rotary Embedding
  base: 10000

optimiser:
  lr: 1e-3

train:
  epochs: 10
  eval_interval: 1
  batch_size: 4
  eval_batch_size: 8
  log_interval: 100
  max_iterations_per_epoch: 10000
  
wandb:
  project: "SaiDl-core-ml-1"
  name: "mqa-learnable-1024"
  
 