_wandb:
    value:
        cli_version: 0.27.0
        e:
            iq1m3rh6xyqcp9rrn8ixravyo5ndwwar:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "12418883584"
                email: f20251402@goa.bits-pilani.ac.in
                executable: /home/shivam/miniconda3/envs/ml/bin/python
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-1a677ef9-a65d-38cd-1d18-e3c159265759
                host: Shivam
                memory:
                    total: "10427117568"
                os: Linux-6.6.114.1-microsoft-standard-WSL2-x86_64-with-glibc2.43
                program: /mnt/d/SAiDL-Summer-Assignment-2026/Sparsity & Optimization/train.py
                python: CPython 3.12.13
                root: /mnt/d/SAiDL-Summer-Assignment-2026/Sparsity & Optimization
                startedAt: "2026-06-06T21:35:20.221583Z"
                writerId: iq1m3rh6xyqcp9rrn8ixravyo5ndwwar
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 51
                - 53
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 51
                - 53
                - 98
            "3":
                - 13
                - 16
            "4": 3.12.13
            "5": 0.27.0
            "6": 5.9.0
            "12": 0.27.0
            "13": linux-x86_64
adalora:
    value:
        ortho_lambda: 0.1
        svd_threshold: 1e-05
model:
    value:
        name_or_path: microsoft/deberta-v3-base
        num_labels: 2
peft:
    value:
        alpha: 16
        rank: 12
        type: lora
sora:
    value:
        proximal_threshold: 0.001
training:
    value:
        batch_size: 16
        block_size: 128
        eval_batch_size: 64
        eval_interval: 1
        learning_rate: 2e-05
        log_interval: 10
        max_iterations_per_epoch: 100
        num_epochs: 1
wandb:
    value:
        name: trial_1
