_wandb:
    value:
        cli_version: 0.27.0
        e:
            w6cyrjnqm37uq9t46z7zf5pll8jm5s2w:
                args:
                    - --config-name
                    - MHA_ALIBI_CONV512_1024
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "12527079424"
                email: f20251402@goa.bits-pilani.ac.in
                executable: /home/shivam/miniconda3/envs/ml/bin/python
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-1a677ef9-a65d-38cd-1d18-e3c159265759
                host: Shivam
                memory:
                    total: "10427109376"
                os: Linux-6.6.114.1-microsoft-standard-WSL2-x86_64-with-glibc2.43
                program: /mnt/d/SAiDL-Summer-Assignment-2026/core_ml/train.py
                python: CPython 3.12.13
                root: /mnt/d/SAiDL-Summer-Assignment-2026/core_ml
                startedAt: "2026-06-07T12:55:00.060185Z"
                writerId: w6cyrjnqm37uq9t46z7zf5pll8jm5s2w
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 11
                - 49
                - 50
            "2":
                - 1
                - 11
                - 49
                - 50
                - 51
            "3":
                - 13
                - 16
            "4": 3.12.13
            "5": 0.27.0
            "6": 5.9.0
            "12": 0.27.0
            "13": linux-x86_64
attention:
    value:
        base: 10000
        group_size: 2
        ngram_size: 512
        positional_encoding: alibi
        sliding_window_mask: false
        type: mha
        use_local_conv: true
        window_size: 512
model:
    value:
        block_size: 1024
        dropout_prob: 0.1
        n_embed: 512
        num_head: 8
        num_layers: 4
optimiser:
    value:
        lr: 0.0001
train:
    value:
        batch_size: 4
        block_size: 8
        epochs: 10
        eval_batch_size: 6
        eval_block_size: 1024
        eval_interval: 1
        log_interval: 100
        max_iterations_per_epoch: 10000
wandb:
    value:
        name: mha-alibi-CONV512-1024
        project: SaiDl-core-ml
